POST /messages HTTP/1.1
Host: localhost:3001
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2ODNkNmVkNjk1Njk1YjQxZGJjNDZjY2QiLCJ1c2VybmFtZSI6ImV2YW5kcm8iLCJpYXQiOjE3NDg4NTY1MzcsImV4cCI6MTc0ODg1NzQzN30.6VOw9AxFYne7fGkcCZdEDLBjghl7RkF29XDhumYVm4g

{
  "title": "Queue test 4",
  "content": "Simple queue test"
}