GET /messages HTTP/1.1
Host: localhost:3001
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2ODNlZDM3ZDEwZTc1YWZiMzhmMzEwZDUiLCJ1c2VybmFtZSI6ImV2YW5kcm8iLCJpYXQiOjE3NDg5OTMyNTMsImV4cCI6MTc0ODk5NDE1M30.zDUb8A7CcZPl8m6VlQ1Esl_VbSLzofvCmXesfDhyVLE
