GET /messages HTTP/1.1
Host: localhost:3001
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2ODNlYmYzMWJhYTc2MzAzZmRhMDg5NmQiLCJ1c2VybmFtZSI6ImV2YW5kcm8iLCJpYXQiOjE3NDg5NDI2NDYsImV4cCI6MTc0ODk0MzU0Nn0.W_S3cafWhqZARBu8nZhlb1v-k3uKTI-xOeDBoPP-T1w
