version: '3'
services:
  db:
    image: mongo
    container_name: notification-worker-db
    env_file: ./.env
    ports:
      - $DB_PORT:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: $DB_USER
      MONGO_INITDB_ROOT_PASSWORD: $DB_PASS
    volumes:
      - ./data:/data/db

  be:
    build:
      context: .
    image: notification-worker-be:latest
    container_name: notification-worker-be
    env_file: ./.env
    ports:
      - $WEB_SERVER_PORT:3000
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - DB_USER=$DB_USER
      - DB_PASS=$DB_PASS
      - DB_HOST=$DB_HOST
      - DB_PORT=$DB_PORT
      - DB_NAME=$DB_NAME
    depends_on:
      - db
    command: npm run start:dev
