version: '3'

networks:
  notification-worker-nt:
    name: notification-worker-nt
    driver: bridge

services:
  db:
    image: mongo
    container_name: notification-worker-db
    env_file: ./.env
    ports:
      - $DB_PORT:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: $DB_USER
      MONGO_INITDB_ROOT_PASSWORD: $DB_PASS
    networks:
      - notification-worker-nt
    volumes:
      - mongo-data:/data:/data/db

  redis:
    image: redis:6-alpine
    container_name: notification-worker-redis
    env_file: ./.env
    ports:
      - $REDIS_PORT:6379
    networks:
      - notification-worker-nt
  be:
    build:
      context: .
    container_name: notification-worker-be
    env_file: ./.env
    ports:
      - $WEB_SERVER_PORT:3001
    networks:
      - notification-worker-nt
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - WEB_SERVER_PORT=$WEB_SERVER_PORT
      - DB_USER=$DB_USER
      - DB_PASS=$DB_PASS
      - DB_HOST=$DB_HOST
      - DB_PORT=27017
      - DB_NAME=$DB_NAME
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
    depends_on:
      - db
      - redis
    command: npm run start:dev

volumes:
  mongo-data:
    name: notification-worker-db-data